/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'customerId' : CustomerId,
  'phone' : IDL.Text,
  'pendingAmount' : IDL.Nat,
  'totalPurchaseAmount' : IDL.Nat,
});
export const InvoiceStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
  'Partial' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const InvoiceItem = IDL.Record({
  'taxPercent' : IDL.Nat,
  'lineTotal' : IDL.Nat,
  'productId' : IDL.Opt(ProductId),
  'productName' : IDL.Text,
  'discount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const InvoiceInput = IDL.Record({
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'total' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'cgst' : IDL.Nat,
  'sgst' : IDL.Nat,
  'dueDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Opt(IDL.Text),
  'discount' : IDL.Nat,
  'customerId' : IDL.Opt(CustomerId),
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Nat,
});
export const InvoiceId = IDL.Nat;
export const Invoice = IDL.Record({
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'total' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'cgst' : IDL.Nat,
  'createdAt' : Timestamp,
  'sgst' : IDL.Nat,
  'dueDate' : IDL.Opt(Timestamp),
  'invoiceId' : InvoiceId,
  'updatedAt' : Timestamp,
  'invoiceNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'discount' : IDL.Nat,
  'customerId' : IDL.Opt(CustomerId),
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Nat,
});
export const ProductInput = IDL.Record({
  'sku' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'taxPercent' : IDL.Nat,
  'supplierName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'sku' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'taxPercent' : IDL.Nat,
  'supplierName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'productId' : ProductId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const BusinessId = IDL.Principal;
export const BusinessProfile = IDL.Record({
  'businessId' : BusinessId,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'todaySales' : IDL.Nat,
  'monthlySales' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'inventoryValue' : IDL.Nat,
  'outstandingPayments' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const StockUpdateId = IDL.Nat;
export const StockUpdate = IDL.Record({
  'changedAt' : Timestamp,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'newQty' : IDL.Nat,
  'updateId' : StockUpdateId,
  'previousQty' : IDL.Nat,
  'changeReason' : IDL.Text,
});
export const PaginatedResult_2 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Customer),
});
export const PaginatedResult_1 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Invoice),
});
export const PaginatedResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Product),
});
export const BusinessProfileInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
  'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deleteBusinessProfile' : IDL.Func([], [IDL.Bool], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getInvoicesByStatus' : IDL.Func(
      [InvoiceStatus],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getStockHistory' : IDL.Func([ProductId], [IDL.Vec(StockUpdate)], ['query']),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedResult_2],
      ['query'],
    ),
  'listInvoices' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult_1], ['query']),
  'listProducts' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
  'saveBusinessProfile' : IDL.Func(
      [BusinessProfileInput],
      [BusinessProfile],
      [],
    ),
  'updateBusinessProfile' : IDL.Func(
      [BusinessProfileInput],
      [IDL.Opt(BusinessProfile)],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, CustomerInput],
      [IDL.Opt(Customer)],
      [],
    ),
  'updateInvoice' : IDL.Func([InvoiceId, InvoiceInput], [IDL.Opt(Invoice)], []),
  'updateInvoicePaymentStatus' : IDL.Func(
      [InvoiceId, PaymentStatus],
      [IDL.Opt(Invoice)],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
  'updateProductStock' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Text],
      [IDL.Opt(StockUpdate)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'customerId' : CustomerId,
    'phone' : IDL.Text,
    'pendingAmount' : IDL.Nat,
    'totalPurchaseAmount' : IDL.Nat,
  });
  const InvoiceStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
    'Partial' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const InvoiceItem = IDL.Record({
    'taxPercent' : IDL.Nat,
    'lineTotal' : IDL.Nat,
    'productId' : IDL.Opt(ProductId),
    'productName' : IDL.Text,
    'discount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const InvoiceInput = IDL.Record({
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'total' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'cgst' : IDL.Nat,
    'sgst' : IDL.Nat,
    'dueDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Opt(IDL.Text),
    'discount' : IDL.Nat,
    'customerId' : IDL.Opt(CustomerId),
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Nat,
  });
  const InvoiceId = IDL.Nat;
  const Invoice = IDL.Record({
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'total' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'cgst' : IDL.Nat,
    'createdAt' : Timestamp,
    'sgst' : IDL.Nat,
    'dueDate' : IDL.Opt(Timestamp),
    'invoiceId' : InvoiceId,
    'updatedAt' : Timestamp,
    'invoiceNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'discount' : IDL.Nat,
    'customerId' : IDL.Opt(CustomerId),
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Nat,
  });
  const ProductInput = IDL.Record({
    'sku' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'taxPercent' : IDL.Nat,
    'supplierName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'taxPercent' : IDL.Nat,
    'supplierName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'productId' : ProductId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const BusinessId = IDL.Principal;
  const BusinessProfile = IDL.Record({
    'businessId' : BusinessId,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'todaySales' : IDL.Nat,
    'monthlySales' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'inventoryValue' : IDL.Nat,
    'outstandingPayments' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const StockUpdateId = IDL.Nat;
  const StockUpdate = IDL.Record({
    'changedAt' : Timestamp,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'newQty' : IDL.Nat,
    'updateId' : StockUpdateId,
    'previousQty' : IDL.Nat,
    'changeReason' : IDL.Text,
  });
  const PaginatedResult_2 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Customer),
  });
  const PaginatedResult_1 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Invoice),
  });
  const PaginatedResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Product),
  });
  const BusinessProfileInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
    'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deleteBusinessProfile' : IDL.Func([], [IDL.Bool], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getInvoicesByStatus' : IDL.Func(
        [InvoiceStatus],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getStockHistory' : IDL.Func(
        [ProductId],
        [IDL.Vec(StockUpdate)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult_2],
        ['query'],
      ),
    'listInvoices' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult_1],
        ['query'],
      ),
    'listProducts' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
    'saveBusinessProfile' : IDL.Func(
        [BusinessProfileInput],
        [BusinessProfile],
        [],
      ),
    'updateBusinessProfile' : IDL.Func(
        [BusinessProfileInput],
        [IDL.Opt(BusinessProfile)],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, CustomerInput],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [InvoiceId, InvoiceInput],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateInvoicePaymentStatus' : IDL.Func(
        [InvoiceId, PaymentStatus],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'updateProductStock' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Text],
        [IDL.Opt(StockUpdate)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };