/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'activeUsers' : bigint,
  'supplierCount' : bigint,
  'expenseCount' : bigint,
  'invoiceCount' : bigint,
  'currentMonthRevenue' : bigint,
  'topMonthRevenue' : bigint,
  'totalExpenses' : bigint,
  'netPL' : bigint,
  'totalUsers' : bigint,
  'customerCount' : bigint,
  'totalRevenue' : bigint,
}
export type BusinessId = Principal;
export interface BusinessProfile {
  'businessId' : BusinessId,
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : string,
  'language' : string,
  'logoUrl' : [] | [string],
  'currency' : string,
  'address' : string,
  'category' : string,
  'phone' : string,
}
export interface BusinessProfileInput {
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : string,
  'language' : string,
  'logoUrl' : [] | [string],
  'currency' : string,
  'address' : string,
  'category' : string,
  'phone' : string,
}
export interface Customer {
  'gstNumber' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'address' : [] | [string],
  'customerId' : CustomerId,
  'phone' : string,
  'pendingAmount' : bigint,
  'totalPurchaseAmount' : bigint,
}
export type CustomerId = bigint;
export interface CustomerInput {
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'phone' : string,
}
export interface DashboardStats {
  'todaySales' : bigint,
  'monthlySales' : bigint,
  'lowStockCount' : bigint,
  'inventoryValue' : bigint,
  'outstandingPayments' : bigint,
  'totalCustomers' : bigint,
}
export interface Expense {
  'id' : ExpenseId,
  'receiptUrl' : [] | [string],
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export type ExpenseCategory = { 'other' : null } |
  { 'marketing' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'utilities' : null } |
  { 'office' : null } |
  { 'rawMaterials' : null } |
  { 'salaries' : null };
export type ExpenseId = bigint;
export interface ExpenseInput {
  'receiptUrl' : [] | [string],
  'date' : Timestamp,
  'description' : string,
  'notes' : [] | [string],
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export interface Invoice {
  'customerName' : string,
  'status' : InvoiceStatus,
  'total' : bigint,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : string,
  'cgst' : bigint,
  'createdAt' : Timestamp,
  'sgst' : bigint,
  'dueDate' : [] | [Timestamp],
  'invoiceId' : InvoiceId,
  'updatedAt' : Timestamp,
  'invoiceNumber' : string,
  'notes' : [] | [string],
  'discount' : bigint,
  'customerId' : [] | [CustomerId],
  'emailSent' : boolean,
  'items' : Array<InvoiceItem>,
  'subtotal' : bigint,
}
export type InvoiceId = bigint;
export interface InvoiceInput {
  'customerName' : string,
  'status' : InvoiceStatus,
  'total' : bigint,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : string,
  'cgst' : bigint,
  'sgst' : bigint,
  'dueDate' : [] | [Timestamp],
  'notes' : [] | [string],
  'discount' : bigint,
  'customerId' : [] | [CustomerId],
  'items' : Array<InvoiceItem>,
  'subtotal' : bigint,
}
export interface InvoiceItem {
  'taxPercent' : bigint,
  'lineTotal' : bigint,
  'productId' : [] | [ProductId],
  'productName' : string,
  'discount' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type InvoiceStatus = { 'Paid' : null } |
  { 'Sent' : null } |
  { 'Draft' : null };
export interface PaginatedResult {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Product>,
}
export interface PaginatedResult_1 {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Invoice>,
}
export interface PaginatedResult_2 {
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<Customer>,
}
export type PaymentStatus = { 'Paid' : null } |
  { 'Unpaid' : null } |
  { 'Partial' : null };
export interface Product {
  'sku' : string,
  'purchasePrice' : bigint,
  'taxPercent' : bigint,
  'supplierName' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'unit' : string,
  'sellingPrice' : bigint,
  'productId' : ProductId,
  'imageUrl' : [] | [string],
  'barcode' : [] | [string],
  'quantity' : bigint,
  'category' : string,
}
export type ProductId = bigint;
export interface ProductInput {
  'sku' : string,
  'purchasePrice' : bigint,
  'taxPercent' : bigint,
  'supplierName' : [] | [string],
  'name' : string,
  'unit' : string,
  'sellingPrice' : bigint,
  'imageUrl' : [] | [string],
  'barcode' : [] | [string],
  'quantity' : bigint,
  'category' : string,
}
export interface Purchase {
  'id' : PurchaseId,
  'status' : PurchaseStatus,
  'supplierName' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'amount' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type PurchaseId = bigint;
export interface PurchaseInput {
  'status' : PurchaseStatus,
  'supplierName' : string,
  'date' : Timestamp,
  'description' : [] | [string],
  'amount' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type PurchaseStatus = { 'cancelled' : null } |
  { 'ordered' : null } |
  { 'received' : null };
export interface StockUpdate {
  'changedAt' : Timestamp,
  'productId' : ProductId,
  'productName' : string,
  'newQty' : bigint,
  'updateId' : StockUpdateId,
  'previousQty' : bigint,
  'changeReason' : string,
}
export type StockUpdateId = bigint;
export interface Supplier {
  'id' : SupplierId,
  'gstNumber' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'email' : [] | [string],
  'totalPurchases' : bigint,
  'updatedAt' : Timestamp,
  'address' : [] | [string],
  'notes' : [] | [string],
  'paymentTerms' : [] | [string],
  'phone' : string,
  'pendingAmount' : bigint,
}
export type SupplierId = bigint;
export interface SupplierInput {
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'notes' : [] | [string],
  'paymentTerms' : [] | [string],
  'phone' : string,
}
export type Timestamp = bigint;
export interface UserInfo {
  'principal' : Principal,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'accountant' : null } |
  { 'owner' : null } |
  { 'staff' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createCustomer' : ActorMethod<[CustomerInput], Customer>,
  'createExpense' : ActorMethod<[ExpenseInput], Expense>,
  'createInvoice' : ActorMethod<[InvoiceInput], Invoice>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'createPurchase' : ActorMethod<[PurchaseInput], Purchase>,
  'createSupplier' : ActorMethod<[SupplierInput], Supplier>,
  'deleteBusinessProfile' : ActorMethod<[], boolean>,
  'deleteCustomer' : ActorMethod<[CustomerId], boolean>,
  'deleteExpense' : ActorMethod<[ExpenseId], boolean>,
  'deleteInvoice' : ActorMethod<[InvoiceId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deletePurchase' : ActorMethod<[PurchaseId], boolean>,
  'deleteSupplier' : ActorMethod<[SupplierId], boolean>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getBusinessProfile' : ActorMethod<[], [] | [BusinessProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExpense' : ActorMethod<[ExpenseId], [] | [Expense]>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  'getInvoicesByCustomer' : ActorMethod<[CustomerId], Array<Invoice>>,
  'getInvoicesByStatus' : ActorMethod<[InvoiceStatus], Array<Invoice>>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getPurchase' : ActorMethod<[PurchaseId], [] | [Purchase]>,
  'getStockHistory' : ActorMethod<[ProductId], Array<StockUpdate>>,
  'getSupplier' : ActorMethod<[SupplierId], [] | [Supplier]>,
  'getTotalExpenses' : ActorMethod<[], bigint>,
  'getUserByPrincipal' : ActorMethod<[Principal], [] | [UserInfo]>,
  'initSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomers' : ActorMethod<[bigint, bigint], PaginatedResult_2>,
  'listExpenses' : ActorMethod<[], Array<Expense>>,
  'listExpensesByCategory' : ActorMethod<[ExpenseCategory], Array<Expense>>,
  'listInvoices' : ActorMethod<[bigint, bigint], PaginatedResult_1>,
  'listProducts' : ActorMethod<[bigint, bigint], PaginatedResult>,
  'listPurchases' : ActorMethod<[], Array<Purchase>>,
  'listPurchasesByStatus' : ActorMethod<[PurchaseStatus], Array<Purchase>>,
  'listPurchasesBySupplier' : ActorMethod<[SupplierId], Array<Purchase>>,
  'listSuppliers' : ActorMethod<[], Array<Supplier>>,
  'listUsers' : ActorMethod<[], Array<UserInfo>>,
  'recordSupplierPayment' : ActorMethod<[SupplierId, bigint], boolean>,
  'recordSupplierPurchase' : ActorMethod<[SupplierId, bigint], boolean>,
  'saveBusinessProfile' : ActorMethod<[BusinessProfileInput], BusinessProfile>,
  'sendInvoiceEmail' : ActorMethod<[InvoiceId], boolean>,
  'updateBusinessProfile' : ActorMethod<
    [BusinessProfileInput],
    [] | [BusinessProfile]
  >,
  'updateCustomer' : ActorMethod<[CustomerId, CustomerInput], [] | [Customer]>,
  'updateExpense' : ActorMethod<[ExpenseId, ExpenseInput], [] | [Expense]>,
  'updateInvoice' : ActorMethod<[InvoiceId, InvoiceInput], [] | [Invoice]>,
  'updateInvoicePaymentStatus' : ActorMethod<
    [InvoiceId, PaymentStatus],
    [] | [Invoice]
  >,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
  'updateProductStock' : ActorMethod<
    [ProductId, bigint, string],
    [] | [StockUpdate]
  >,
  'updatePurchase' : ActorMethod<[PurchaseId, PurchaseInput], [] | [Purchase]>,
  'updateSupplier' : ActorMethod<[SupplierId, SupplierInput], [] | [Supplier]>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], [] | [UserInfo]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];