/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CustomerInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CustomerId = IDL.Nat;
export const Customer = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'customerId' : CustomerId,
  'phone' : IDL.Text,
  'pendingAmount' : IDL.Nat,
  'totalPurchaseAmount' : IDL.Nat,
});
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'marketing' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'utilities' : IDL.Null,
  'office' : IDL.Null,
  'rawMaterials' : IDL.Null,
  'salaries' : IDL.Null,
});
export const ExpenseInput = IDL.Record({
  'receiptUrl' : IDL.Opt(IDL.Text),
  'date' : Timestamp,
  'description' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'category' : ExpenseCategory,
  'amount' : IDL.Int,
});
export const ExpenseId = IDL.Nat;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'receiptUrl' : IDL.Opt(IDL.Text),
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'category' : ExpenseCategory,
  'amount' : IDL.Int,
});
export const InvoiceStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'Paid' : IDL.Null,
  'Unpaid' : IDL.Null,
  'Partial' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const InvoiceItem = IDL.Record({
  'taxPercent' : IDL.Nat,
  'lineTotal' : IDL.Nat,
  'productId' : IDL.Opt(ProductId),
  'productName' : IDL.Text,
  'discount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const InvoiceInput = IDL.Record({
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'total' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'cgst' : IDL.Nat,
  'sgst' : IDL.Nat,
  'dueDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Opt(IDL.Text),
  'discount' : IDL.Nat,
  'customerId' : IDL.Opt(CustomerId),
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Nat,
});
export const InvoiceId = IDL.Nat;
export const Invoice = IDL.Record({
  'customerName' : IDL.Text,
  'status' : InvoiceStatus,
  'total' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'customerPhone' : IDL.Text,
  'cgst' : IDL.Nat,
  'createdAt' : Timestamp,
  'sgst' : IDL.Nat,
  'dueDate' : IDL.Opt(Timestamp),
  'invoiceId' : InvoiceId,
  'updatedAt' : Timestamp,
  'invoiceNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'discount' : IDL.Nat,
  'customerId' : IDL.Opt(CustomerId),
  'emailSent' : IDL.Bool,
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Nat,
});
export const ProductInput = IDL.Record({
  'sku' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'taxPercent' : IDL.Nat,
  'supplierName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const Product = IDL.Record({
  'sku' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'taxPercent' : IDL.Nat,
  'supplierName' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'productId' : ProductId,
  'imageUrl' : IDL.Opt(IDL.Text),
  'barcode' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});
export const PurchaseStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'ordered' : IDL.Null,
  'received' : IDL.Null,
});
export const SupplierId = IDL.Nat;
export const PurchaseInput = IDL.Record({
  'status' : PurchaseStatus,
  'supplierName' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'amount' : IDL.Int,
  'supplierId' : IDL.Opt(SupplierId),
});
export const PurchaseId = IDL.Nat;
export const Purchase = IDL.Record({
  'id' : PurchaseId,
  'status' : PurchaseStatus,
  'supplierName' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'amount' : IDL.Int,
  'supplierId' : IDL.Opt(SupplierId),
});
export const SupplierInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'paymentTerms' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Supplier = IDL.Record({
  'id' : SupplierId,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'totalPurchases' : IDL.Int,
  'updatedAt' : Timestamp,
  'address' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'paymentTerms' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'pendingAmount' : IDL.Int,
});
export const AdminStats = IDL.Record({
  'activeUsers' : IDL.Nat,
  'supplierCount' : IDL.Nat,
  'expenseCount' : IDL.Nat,
  'invoiceCount' : IDL.Nat,
  'currentMonthRevenue' : IDL.Int,
  'topMonthRevenue' : IDL.Int,
  'totalExpenses' : IDL.Int,
  'netPL' : IDL.Int,
  'totalUsers' : IDL.Nat,
  'customerCount' : IDL.Nat,
  'totalRevenue' : IDL.Int,
});
export const BusinessId = IDL.Principal;
export const BusinessProfile = IDL.Record({
  'businessId' : BusinessId,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'todaySales' : IDL.Nat,
  'monthlySales' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'inventoryValue' : IDL.Nat,
  'outstandingPayments' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const StockUpdateId = IDL.Nat;
export const StockUpdate = IDL.Record({
  'changedAt' : Timestamp,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'newQty' : IDL.Nat,
  'updateId' : StockUpdateId,
  'previousQty' : IDL.Nat,
  'changeReason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'accountant' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const PaginatedResult_2 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Customer),
});
export const PaginatedResult_1 = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Invoice),
});
export const PaginatedResult = IDL.Record({
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(Product),
});
export const BusinessProfileInput = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'address' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
  'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
  'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'createPurchase' : IDL.Func([PurchaseInput], [Purchase], []),
  'createSupplier' : IDL.Func([SupplierInput], [Supplier], []),
  'deleteBusinessProfile' : IDL.Func([], [IDL.Bool], []),
  'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
  'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
  'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deletePurchase' : IDL.Func([PurchaseId], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getInvoicesByCustomer' : IDL.Func(
      [CustomerId],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getInvoicesByStatus' : IDL.Func(
      [InvoiceStatus],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getPurchase' : IDL.Func([PurchaseId], [IDL.Opt(Purchase)], ['query']),
  'getStockHistory' : IDL.Func([ProductId], [IDL.Vec(StockUpdate)], ['query']),
  'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
  'getTotalExpenses' : IDL.Func([], [IDL.Int], ['query']),
  'getUserByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserInfo)],
      ['query'],
    ),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [PaginatedResult_2],
      ['query'],
    ),
  'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'listExpensesByCategory' : IDL.Func(
      [ExpenseCategory],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'listInvoices' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult_1], ['query']),
  'listProducts' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
  'listPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'listPurchasesByStatus' : IDL.Func(
      [PurchaseStatus],
      [IDL.Vec(Purchase)],
      ['query'],
    ),
  'listPurchasesBySupplier' : IDL.Func(
      [SupplierId],
      [IDL.Vec(Purchase)],
      ['query'],
    ),
  'listSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'recordSupplierPayment' : IDL.Func([SupplierId, IDL.Int], [IDL.Bool], []),
  'recordSupplierPurchase' : IDL.Func([SupplierId, IDL.Int], [IDL.Bool], []),
  'saveBusinessProfile' : IDL.Func(
      [BusinessProfileInput],
      [BusinessProfile],
      [],
    ),
  'sendInvoiceEmail' : IDL.Func([InvoiceId], [IDL.Bool], []),
  'updateBusinessProfile' : IDL.Func(
      [BusinessProfileInput],
      [IDL.Opt(BusinessProfile)],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [CustomerId, CustomerInput],
      [IDL.Opt(Customer)],
      [],
    ),
  'updateExpense' : IDL.Func([ExpenseId, ExpenseInput], [IDL.Opt(Expense)], []),
  'updateInvoice' : IDL.Func([InvoiceId, InvoiceInput], [IDL.Opt(Invoice)], []),
  'updateInvoicePaymentStatus' : IDL.Func(
      [InvoiceId, PaymentStatus],
      [IDL.Opt(Invoice)],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
  'updateProductStock' : IDL.Func(
      [ProductId, IDL.Nat, IDL.Text],
      [IDL.Opt(StockUpdate)],
      [],
    ),
  'updatePurchase' : IDL.Func(
      [PurchaseId, PurchaseInput],
      [IDL.Opt(Purchase)],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [SupplierId, SupplierInput],
      [IDL.Opt(Supplier)],
      [],
    ),
  'updateUserRole' : IDL.Func(
      [IDL.Principal, UserRole],
      [IDL.Opt(UserInfo)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CustomerInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CustomerId = IDL.Nat;
  const Customer = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'customerId' : CustomerId,
    'phone' : IDL.Text,
    'pendingAmount' : IDL.Nat,
    'totalPurchaseAmount' : IDL.Nat,
  });
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'marketing' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'utilities' : IDL.Null,
    'office' : IDL.Null,
    'rawMaterials' : IDL.Null,
    'salaries' : IDL.Null,
  });
  const ExpenseInput = IDL.Record({
    'receiptUrl' : IDL.Opt(IDL.Text),
    'date' : Timestamp,
    'description' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'category' : ExpenseCategory,
    'amount' : IDL.Int,
  });
  const ExpenseId = IDL.Nat;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'receiptUrl' : IDL.Opt(IDL.Text),
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'category' : ExpenseCategory,
    'amount' : IDL.Int,
  });
  const InvoiceStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
  });
  const PaymentStatus = IDL.Variant({
    'Paid' : IDL.Null,
    'Unpaid' : IDL.Null,
    'Partial' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const InvoiceItem = IDL.Record({
    'taxPercent' : IDL.Nat,
    'lineTotal' : IDL.Nat,
    'productId' : IDL.Opt(ProductId),
    'productName' : IDL.Text,
    'discount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const InvoiceInput = IDL.Record({
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'total' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'cgst' : IDL.Nat,
    'sgst' : IDL.Nat,
    'dueDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Opt(IDL.Text),
    'discount' : IDL.Nat,
    'customerId' : IDL.Opt(CustomerId),
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Nat,
  });
  const InvoiceId = IDL.Nat;
  const Invoice = IDL.Record({
    'customerName' : IDL.Text,
    'status' : InvoiceStatus,
    'total' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'customerPhone' : IDL.Text,
    'cgst' : IDL.Nat,
    'createdAt' : Timestamp,
    'sgst' : IDL.Nat,
    'dueDate' : IDL.Opt(Timestamp),
    'invoiceId' : InvoiceId,
    'updatedAt' : Timestamp,
    'invoiceNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'discount' : IDL.Nat,
    'customerId' : IDL.Opt(CustomerId),
    'emailSent' : IDL.Bool,
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Nat,
  });
  const ProductInput = IDL.Record({
    'sku' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'taxPercent' : IDL.Nat,
    'supplierName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'taxPercent' : IDL.Nat,
    'supplierName' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'productId' : ProductId,
    'imageUrl' : IDL.Opt(IDL.Text),
    'barcode' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  const PurchaseStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'ordered' : IDL.Null,
    'received' : IDL.Null,
  });
  const SupplierId = IDL.Nat;
  const PurchaseInput = IDL.Record({
    'status' : PurchaseStatus,
    'supplierName' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'amount' : IDL.Int,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const PurchaseId = IDL.Nat;
  const Purchase = IDL.Record({
    'id' : PurchaseId,
    'status' : PurchaseStatus,
    'supplierName' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'amount' : IDL.Int,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const SupplierInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'paymentTerms' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Supplier = IDL.Record({
    'id' : SupplierId,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'totalPurchases' : IDL.Int,
    'updatedAt' : Timestamp,
    'address' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'paymentTerms' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'pendingAmount' : IDL.Int,
  });
  const AdminStats = IDL.Record({
    'activeUsers' : IDL.Nat,
    'supplierCount' : IDL.Nat,
    'expenseCount' : IDL.Nat,
    'invoiceCount' : IDL.Nat,
    'currentMonthRevenue' : IDL.Int,
    'topMonthRevenue' : IDL.Int,
    'totalExpenses' : IDL.Int,
    'netPL' : IDL.Int,
    'totalUsers' : IDL.Nat,
    'customerCount' : IDL.Nat,
    'totalRevenue' : IDL.Int,
  });
  const BusinessId = IDL.Principal;
  const BusinessProfile = IDL.Record({
    'businessId' : BusinessId,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'todaySales' : IDL.Nat,
    'monthlySales' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'inventoryValue' : IDL.Nat,
    'outstandingPayments' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const StockUpdateId = IDL.Nat;
  const StockUpdate = IDL.Record({
    'changedAt' : Timestamp,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'newQty' : IDL.Nat,
    'updateId' : StockUpdateId,
    'previousQty' : IDL.Nat,
    'changeReason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'accountant' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const PaginatedResult_2 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Customer),
  });
  const PaginatedResult_1 = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Invoice),
  });
  const PaginatedResult = IDL.Record({
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(Product),
  });
  const BusinessProfileInput = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'address' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
    'createExpense' : IDL.Func([ExpenseInput], [Expense], []),
    'createInvoice' : IDL.Func([InvoiceInput], [Invoice], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'createPurchase' : IDL.Func([PurchaseInput], [Purchase], []),
    'createSupplier' : IDL.Func([SupplierInput], [Supplier], []),
    'deleteBusinessProfile' : IDL.Func([], [IDL.Bool], []),
    'deleteCustomer' : IDL.Func([CustomerId], [IDL.Bool], []),
    'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
    'deleteInvoice' : IDL.Func([InvoiceId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deletePurchase' : IDL.Func([PurchaseId], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getBusinessProfile' : IDL.Func([], [IDL.Opt(BusinessProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [CustomerId],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getInvoicesByStatus' : IDL.Func(
        [InvoiceStatus],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getPurchase' : IDL.Func([PurchaseId], [IDL.Opt(Purchase)], ['query']),
    'getStockHistory' : IDL.Func(
        [ProductId],
        [IDL.Vec(StockUpdate)],
        ['query'],
      ),
    'getSupplier' : IDL.Func([SupplierId], [IDL.Opt(Supplier)], ['query']),
    'getTotalExpenses' : IDL.Func([], [IDL.Int], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserInfo)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult_2],
        ['query'],
      ),
    'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'listExpensesByCategory' : IDL.Func(
        [ExpenseCategory],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'listInvoices' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [PaginatedResult_1],
        ['query'],
      ),
    'listProducts' : IDL.Func([IDL.Nat, IDL.Nat], [PaginatedResult], ['query']),
    'listPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'listPurchasesByStatus' : IDL.Func(
        [PurchaseStatus],
        [IDL.Vec(Purchase)],
        ['query'],
      ),
    'listPurchasesBySupplier' : IDL.Func(
        [SupplierId],
        [IDL.Vec(Purchase)],
        ['query'],
      ),
    'listSuppliers' : IDL.Func([], [IDL.Vec(Supplier)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'recordSupplierPayment' : IDL.Func([SupplierId, IDL.Int], [IDL.Bool], []),
    'recordSupplierPurchase' : IDL.Func([SupplierId, IDL.Int], [IDL.Bool], []),
    'saveBusinessProfile' : IDL.Func(
        [BusinessProfileInput],
        [BusinessProfile],
        [],
      ),
    'sendInvoiceEmail' : IDL.Func([InvoiceId], [IDL.Bool], []),
    'updateBusinessProfile' : IDL.Func(
        [BusinessProfileInput],
        [IDL.Opt(BusinessProfile)],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [CustomerId, CustomerInput],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateExpense' : IDL.Func(
        [ExpenseId, ExpenseInput],
        [IDL.Opt(Expense)],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [InvoiceId, InvoiceInput],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateInvoicePaymentStatus' : IDL.Func(
        [InvoiceId, PaymentStatus],
        [IDL.Opt(Invoice)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'updateProductStock' : IDL.Func(
        [ProductId, IDL.Nat, IDL.Text],
        [IDL.Opt(StockUpdate)],
        [],
      ),
    'updatePurchase' : IDL.Func(
        [PurchaseId, PurchaseInput],
        [IDL.Opt(Purchase)],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [SupplierId, SupplierInput],
        [IDL.Opt(Supplier)],
        [],
      ),
    'updateUserRole' : IDL.Func(
        [IDL.Principal, UserRole],
        [IDL.Opt(UserInfo)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };