/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InvoiceInput {
    customerName: string;
    status: InvoiceStatus;
    total: bigint;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    sgst: bigint;
    dueDate?: Timestamp;
    notes?: string;
    discount: bigint;
    customerId?: CustomerId;
    items: Array<InvoiceItem>;
    subtotal: bigint;
}
export interface ProductInput {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName?: string;
    name: string;
    unit: string;
    sellingPrice: bigint;
    imageUrl?: string;
    barcode?: string;
    quantity: bigint;
    category: string;
}
export type Timestamp = bigint;
export interface PaginatedResult_1 {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Invoice>;
}
export interface InvoiceItem {
    taxPercent: bigint;
    lineTotal: bigint;
    productId?: ProductId;
    productName: string;
    discount: bigint;
    quantity: bigint;
    unitPrice: bigint;
}
export interface BusinessProfileInput {
    gstNumber?: string;
    name: string;
    email: string;
    language: string;
    logoUrl?: string;
    currency: string;
    address: string;
    category: string;
    phone: string;
}
export type StockUpdateId = bigint;
export interface PaginatedResult_2 {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Customer>;
}
export interface Invoice {
    customerName: string;
    status: InvoiceStatus;
    total: bigint;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    createdAt: Timestamp;
    sgst: bigint;
    dueDate?: Timestamp;
    invoiceId: InvoiceId;
    updatedAt: Timestamp;
    invoiceNumber: string;
    notes?: string;
    discount: bigint;
    customerId?: CustomerId;
    items: Array<InvoiceItem>;
    subtotal: bigint;
}
export interface DashboardStats {
    todaySales: bigint;
    monthlySales: bigint;
    lowStockCount: bigint;
    inventoryValue: bigint;
    outstandingPayments: bigint;
    totalCustomers: bigint;
}
export interface Customer {
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    address?: string;
    customerId: CustomerId;
    phone: string;
    pendingAmount: bigint;
    totalPurchaseAmount: bigint;
}
export interface CustomerInput {
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    phone: string;
}
export type BusinessId = Principal;
export interface StockUpdate {
    changedAt: Timestamp;
    productId: ProductId;
    productName: string;
    newQty: bigint;
    updateId: StockUpdateId;
    previousQty: bigint;
    changeReason: string;
}
export type CustomerId = bigint;
export interface PaginatedResult {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Product>;
}
export type InvoiceId = bigint;
export type ProductId = bigint;
export interface BusinessProfile {
    businessId: BusinessId;
    gstNumber?: string;
    name: string;
    email: string;
    language: string;
    logoUrl?: string;
    currency: string;
    address: string;
    category: string;
    phone: string;
}
export interface Product {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName?: string;
    name: string;
    createdAt: Timestamp;
    unit: string;
    sellingPrice: bigint;
    productId: ProductId;
    imageUrl?: string;
    barcode?: string;
    quantity: bigint;
    category: string;
}
export enum InvoiceStatus {
    Paid = "Paid",
    Sent = "Sent",
    Draft = "Draft"
}
export enum PaymentStatus {
    Paid = "Paid",
    Unpaid = "Unpaid",
    Partial_ = "Partial"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCustomer(input: CustomerInput): Promise<Customer>;
    createInvoice(input: InvoiceInput): Promise<Invoice>;
    createProduct(input: ProductInput): Promise<Product>;
    deleteBusinessProfile(): Promise<boolean>;
    deleteCustomer(id: CustomerId): Promise<boolean>;
    deleteInvoice(id: InvoiceId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getBusinessProfile(): Promise<BusinessProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: CustomerId): Promise<Customer | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getInvoice(id: InvoiceId): Promise<Invoice | null>;
    getInvoicesByCustomer(customerId: CustomerId): Promise<Array<Invoice>>;
    getInvoicesByStatus(status: InvoiceStatus): Promise<Array<Invoice>>;
    getLowStockProducts(): Promise<Array<Product>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getStockHistory(id: ProductId): Promise<Array<StockUpdate>>;
    initSeedData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listCustomers(page: bigint, pageSize: bigint): Promise<PaginatedResult_2>;
    listInvoices(page: bigint, pageSize: bigint): Promise<PaginatedResult_1>;
    listProducts(page: bigint, pageSize: bigint): Promise<PaginatedResult>;
    saveBusinessProfile(input: BusinessProfileInput): Promise<BusinessProfile>;
    updateBusinessProfile(input: BusinessProfileInput): Promise<BusinessProfile | null>;
    updateCustomer(id: CustomerId, input: CustomerInput): Promise<Customer | null>;
    updateInvoice(id: InvoiceId, input: InvoiceInput): Promise<Invoice | null>;
    updateInvoicePaymentStatus(id: InvoiceId, paymentStatus: PaymentStatus): Promise<Invoice | null>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
    updateProductStock(id: ProductId, newQty: bigint, reason: string): Promise<StockUpdate | null>;
}
import type { BusinessId as _BusinessId, BusinessProfile as _BusinessProfile, BusinessProfileInput as _BusinessProfileInput, Customer as _Customer, CustomerId as _CustomerId, CustomerInput as _CustomerInput, Invoice as _Invoice, InvoiceId as _InvoiceId, InvoiceInput as _InvoiceInput, InvoiceItem as _InvoiceItem, InvoiceStatus as _InvoiceStatus, PaginatedResult as _PaginatedResult, PaginatedResult_1 as _PaginatedResult_1, PaginatedResult_2 as _PaginatedResult_2, PaymentStatus as _PaymentStatus, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, StockUpdate as _StockUpdate, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCustomer(arg0: CustomerInput): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_CustomerInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Customer_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_CustomerInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Customer_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: InvoiceInput): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_InvoiceInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Invoice_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_InvoiceInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Invoice_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_ProductInput_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_ProductInput_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteBusinessProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusinessProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusinessProfile();
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: InvoiceId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getBusinessProfile(): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInvoice(arg0: InvoiceId): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomer(arg0: CustomerId): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomer(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomer(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByStatus(arg0: InvoiceStatus): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByStatus(to_candid_InvoiceStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByStatus(to_candid_InvoiceStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStockHistory(arg0: ProductId): Promise<Array<StockUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStockHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStockHistory(arg0);
            return result;
        }
    }
    async initSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomers(arg0: bigint, arg1: bigint): Promise<PaginatedResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers(arg0, arg1);
                return from_candid_PaginatedResult_2_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers(arg0, arg1);
            return from_candid_PaginatedResult_2_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(arg0: bigint, arg1: bigint): Promise<PaginatedResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices(arg0, arg1);
                return from_candid_PaginatedResult_1_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices(arg0, arg1);
            return from_candid_PaginatedResult_1_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: bigint, arg1: bigint): Promise<PaginatedResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(arg0, arg1);
                return from_candid_PaginatedResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(arg0, arg1);
            return from_candid_PaginatedResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveBusinessProfile(arg0: BusinessProfileInput): Promise<BusinessProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BusinessProfile_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBusinessProfile(to_candid_BusinessProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BusinessProfile_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBusinessProfile(arg0: BusinessProfileInput): Promise<BusinessProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusinessProfile(to_candid_BusinessProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusinessProfile(to_candid_BusinessProfileInput_n50(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: CustomerInput): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoice(arg0: InvoiceId, arg1: InvoiceInput): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, to_candid_InvoiceInput_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, to_candid_InvoiceInput_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoicePaymentStatus(arg0: InvoiceId, arg1: PaymentStatus): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoicePaymentStatus(arg0, to_candid_PaymentStatus_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoicePaymentStatus(arg0, to_candid_PaymentStatus_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n29(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n29(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProductStock(arg0: ProductId, arg1: bigint, arg2: string): Promise<StockUpdate | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStock(arg0, arg1, arg2);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStock(arg0, arg1, arg2);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BusinessProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfile): BusinessProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceItem_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceItem): InvoiceItem {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_1_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_1): PaginatedResult_1 {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_2_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult_2): PaginatedResult_2 {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PaginatedResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaginatedResult): PaginatedResult {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerId]): CustomerId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductId]): ProductId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfile]): BusinessProfile | null {
    return value.length === 0 ? null : from_candid_BusinessProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StockUpdate]): StockUpdate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _InvoiceStatus;
    total: bigint;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    createdAt: _Timestamp;
    sgst: bigint;
    dueDate: [] | [_Timestamp];
    invoiceId: _InvoiceId;
    updatedAt: _Timestamp;
    invoiceNumber: string;
    notes: [] | [string];
    discount: bigint;
    customerId: [] | [_CustomerId];
    items: Array<_InvoiceItem>;
    subtotal: bigint;
}): {
    customerName: string;
    status: InvoiceStatus;
    total: bigint;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    createdAt: Timestamp;
    sgst: bigint;
    dueDate?: Timestamp;
    invoiceId: InvoiceId;
    updatedAt: Timestamp;
    invoiceNumber: string;
    notes?: string;
    discount: bigint;
    customerId?: CustomerId;
    items: Array<InvoiceItem>;
    subtotal: bigint;
} {
    return {
        customerName: value.customerName,
        status: from_candid_InvoiceStatus_n19(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentStatus: from_candid_PaymentStatus_n21(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        cgst: value.cgst,
        createdAt: value.createdAt,
        sgst: value.sgst,
        dueDate: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.dueDate)),
        invoiceId: value.invoiceId,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        notes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.notes)),
        discount: value.discount,
        customerId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.customerId)),
        items: from_candid_vec_n25(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxPercent: bigint;
    lineTotal: bigint;
    productId: [] | [_ProductId];
    productName: string;
    discount: bigint;
    quantity: bigint;
    unitPrice: bigint;
}): {
    taxPercent: bigint;
    lineTotal: bigint;
    productId?: ProductId;
    productName: string;
    discount: bigint;
    quantity: bigint;
    unitPrice: bigint;
} {
    return {
        taxPercent: value.taxPercent,
        lineTotal: value.lineTotal,
        productId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.productId)),
        productName: value.productName,
        discount: value.discount,
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName: [] | [string];
    name: string;
    createdAt: _Timestamp;
    unit: string;
    sellingPrice: bigint;
    productId: _ProductId;
    imageUrl: [] | [string];
    barcode: [] | [string];
    quantity: bigint;
    category: string;
}): {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName?: string;
    name: string;
    createdAt: Timestamp;
    unit: string;
    sellingPrice: bigint;
    productId: ProductId;
    imageUrl?: string;
    barcode?: string;
    quantity: bigint;
    category: string;
} {
    return {
        sku: value.sku,
        purchasePrice: value.purchasePrice,
        taxPercent: value.taxPercent,
        supplierName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.supplierName)),
        name: value.name,
        createdAt: value.createdAt,
        unit: value.unit,
        sellingPrice: value.sellingPrice,
        productId: value.productId,
        imageUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.imageUrl)),
        barcode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.barcode)),
        quantity: value.quantity,
        category: value.category
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessId: _BusinessId;
    gstNumber: [] | [string];
    name: string;
    email: string;
    language: string;
    logoUrl: [] | [string];
    currency: string;
    address: string;
    category: string;
    phone: string;
}): {
    businessId: BusinessId;
    gstNumber?: string;
    name: string;
    email: string;
    language: string;
    logoUrl?: string;
    currency: string;
    address: string;
    category: string;
    phone: string;
} {
    return {
        businessId: value.businessId,
        gstNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        email: value.email,
        language: value.language,
        logoUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.logoUrl)),
        currency: value.currency,
        address: value.address,
        category: value.category,
        phone: value.phone
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Customer>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Customer>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n45(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Invoice>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Invoice>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n40(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<_Product>;
}): {
    total: bigint;
    page: bigint;
    pageSize: bigint;
    items: Array<Product>;
} {
    return {
        total: value.total,
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n41(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber: [] | [string];
    name: string;
    createdAt: _Timestamp;
    email: [] | [string];
    address: [] | [string];
    customerId: _CustomerId;
    phone: string;
    pendingAmount: bigint;
    totalPurchaseAmount: bigint;
}): {
    gstNumber?: string;
    name: string;
    createdAt: Timestamp;
    email?: string;
    address?: string;
    customerId: CustomerId;
    phone: string;
    pendingAmount: bigint;
    totalPurchaseAmount: bigint;
} {
    return {
        gstNumber: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.address)),
        customerId: value.customerId,
        phone: value.phone,
        pendingAmount: value.pendingAmount,
        totalPurchaseAmount: value.totalPurchaseAmount
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Sent: null;
} | {
    Draft: null;
}): InvoiceStatus {
    return "Paid" in value ? InvoiceStatus.Paid : "Sent" in value ? InvoiceStatus.Sent : "Draft" in value ? InvoiceStatus.Draft : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Paid: null;
} | {
    Unpaid: null;
} | {
    Partial: null;
}): PaymentStatus {
    return "Paid" in value ? PaymentStatus.Paid : "Unpaid" in value ? PaymentStatus.Unpaid : "Partial" in value ? PaymentStatus.Partial : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceItem>): Array<InvoiceItem> {
    return value.map((x)=>from_candid_InvoiceItem_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n5(_uploadFile, _downloadFile, x));
}
function to_candid_BusinessProfileInput_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfileInput): _BusinessProfileInput {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): _CustomerInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceInput): _InvoiceInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceItem): _InvoiceItem {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxPercent: bigint;
    lineTotal: bigint;
    productId?: ProductId;
    productName: string;
    discount: bigint;
    quantity: bigint;
    unitPrice: bigint;
}): {
    taxPercent: bigint;
    lineTotal: bigint;
    productId: [] | [_ProductId];
    productName: string;
    discount: bigint;
    quantity: bigint;
    unitPrice: bigint;
} {
    return {
        taxPercent: value.taxPercent,
        lineTotal: value.lineTotal,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        productName: value.productName,
        discount: value.discount,
        quantity: value.quantity,
        unitPrice: value.unitPrice
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName?: string;
    name: string;
    unit: string;
    sellingPrice: bigint;
    imageUrl?: string;
    barcode?: string;
    quantity: bigint;
    category: string;
}): {
    sku: string;
    purchasePrice: bigint;
    taxPercent: bigint;
    supplierName: [] | [string];
    name: string;
    unit: string;
    sellingPrice: bigint;
    imageUrl: [] | [string];
    barcode: [] | [string];
    quantity: bigint;
    category: string;
} {
    return {
        sku: value.sku,
        purchasePrice: value.purchasePrice,
        taxPercent: value.taxPercent,
        supplierName: value.supplierName ? candid_some(value.supplierName) : candid_none(),
        name: value.name,
        unit: value.unit,
        sellingPrice: value.sellingPrice,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        barcode: value.barcode ? candid_some(value.barcode) : candid_none(),
        quantity: value.quantity,
        category: value.category
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    phone: string;
}): {
    gstNumber: [] | [string];
    name: string;
    email: [] | [string];
    address: [] | [string];
    phone: string;
} {
    return {
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber?: string;
    name: string;
    email: string;
    language: string;
    logoUrl?: string;
    currency: string;
    address: string;
    category: string;
    phone: string;
}): {
    gstNumber: [] | [string];
    name: string;
    email: string;
    language: string;
    logoUrl: [] | [string];
    currency: string;
    address: string;
    category: string;
    phone: string;
} {
    return {
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        email: value.email,
        language: value.language,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none(),
        currency: value.currency,
        address: value.address,
        category: value.category,
        phone: value.phone
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: InvoiceStatus;
    total: bigint;
    paymentStatus: PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    sgst: bigint;
    dueDate?: Timestamp;
    notes?: string;
    discount: bigint;
    customerId?: CustomerId;
    items: Array<InvoiceItem>;
    subtotal: bigint;
}): {
    customerName: string;
    status: _InvoiceStatus;
    total: bigint;
    paymentStatus: _PaymentStatus;
    customerPhone: string;
    cgst: bigint;
    sgst: bigint;
    dueDate: [] | [_Timestamp];
    notes: [] | [string];
    discount: bigint;
    customerId: [] | [_CustomerId];
    items: Array<_InvoiceItem>;
    subtotal: bigint;
} {
    return {
        customerName: value.customerName,
        status: to_candid_InvoiceStatus_n10(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentStatus: to_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.paymentStatus),
        customerPhone: value.customerPhone,
        cgst: value.cgst,
        sgst: value.sgst,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        discount: value.discount,
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        items: to_candid_vec_n14(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    Paid: null;
} | {
    Sent: null;
} | {
    Draft: null;
} {
    return value == InvoiceStatus.Paid ? {
        Paid: null
    } : value == InvoiceStatus.Sent ? {
        Sent: null
    } : value == InvoiceStatus.Draft ? {
        Draft: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    Paid: null;
} | {
    Unpaid: null;
} | {
    Partial: null;
} {
    return value == PaymentStatus.Paid ? {
        Paid: null
    } : value == PaymentStatus.Unpaid ? {
        Unpaid: null
    } : value == PaymentStatus.Partial ? {
        Partial_: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InvoiceItem>): Array<_InvoiceItem> {
    return value.map((x)=>to_candid_InvoiceItem_n15(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
